
version: '3.8'

services:
  testdatagen:
    build:
      context: ..
      dockerfile: dev-setup/Dockerfile
    volumes:
      - ..:/app
      - testdatagen_venv:/app/.venv
    ports:
      - "8000:8000"  # For web API
    environment:
      - PYTHONPATH=/app
    command: bash
    tty: true
    stdin_open: true

volumes:
  testdatagen_venv:
